language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
install:
  - yarn
script:
  - yarn build
  - yarn test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

